source:rubygems

gem "rails", "3.2.1"
gem "sqlite3"
gem "jquery-rails"
gem "devise"
gem "haml"
gem "letter_opener", group: :development
gem "resque"
gem "resque-retry"
gem "populator"
gem "faker"
gem "settingslogic"
gem "rest-client"
