source 'https://rubygems.org'

gem 'rails', '3.2.1'

gem 'sqlite3'
gem 'bcrypt-ruby', :require => 'bcrypt'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'        # jquery + rails
gem 'paperclip', '~> 2.7' # attachments
gem 'cancan'              # authorization
gem 'delayed_job'         # background processing
gem 'populator'           # seeding
gem 'faker'               # seeding