source 'https://rubygems.org'

gem 'rails', '3.2.1'

gem 'sqlite3'
gem 'bcrypt-ruby', :require => 'bcrypt'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer'
  gem 'uglifier', '>= 1.0.3'
end

gem 'json'                      # may be a dependency already
gem 'jquery-rails'              # jquery + rails
gem 'paperclip', '~> 2.7'       # attachments
gem 'cancan'                    # authorization
gem 'delayed_job_active_record' # background processing
gem 'populator'                 # seeding
gem 'faker'                     # seeding
gem 'settingslogic'             # putting sensitive info not to check in (api keys)
gem 'rest-client'               # for virus total communication
gem 'surveyor'
