#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

ENV['GMAIL_EMAIL']    = "goodapp.confirm@gmail.com"
ENV['GMAIL_PASSWORD'] = ">2q3&X__~@s/"

require File.expand_path('../config/application', __FILE__)

Web::Application.load_tasks
